version: "3.3"

services:
  centos1:
    image: "centos"
    tty: true
    networks:
      - frontend

  centos2:
    image: "centos"
    tty: true
    networks:
      - frontend
      - backend

  nginx:
    image: "nginx"
    tty: true
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - frontend

  php:
    image: "twosee/swoole"
    ports:
      - 7801
      - 7802
    tty: true
    networks:
      - frontend
      - backend

  mysql:
    image: "mysql"
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - backend

  redis:
    image: "redis"
    ports:
      - 6379
    networks:
      - backend

networks:
  frontend:
  backend:
