version: "3.3"

services:
  nginx:
    build: ./nginx
    ports:
      - "8899:80"
    volumes:
      - ./nginx/logs:/var/logs/nginx/:rw
      - ./cgi/MyAdmin:/var/www
    networks:
      - backend

  cgi:
    build: ./cgi
    ports:
      - "9000"
    tty: true
    volumes:  
      - ./cgi/MyAdmin:/var/www
    networks:
       - backend

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/data/mysql 
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - backend
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
